name: CI Pipeline Karsajobs UI

on:
  push:
    branches:
      - 'karsajobs-ui'
  pull_request:
    branches:
      - 'karsajobs-ui'

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    needs: lint-dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/sofyanegil/karsajobs-ui:latest .
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u sofyanegil --password-stdin
          docker push ghcr.io/sofyanegil/karsajobs-ui:latest
