name: CI Pipeline

on:
  push:
    branches:
      - 'karsajobs'
  pull_request:
    branches:
      - 'karsajobs'

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  test-app:
    runs-on: ubuntu-latest
    needs: lint-dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run unit tests
        run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest
    needs: test-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/sofyanegil/karsajobs:latest .
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u sofyanegil --password-stdin
          docker push ghcr.io/sofyanegil/karsajobs:latest
